# Generation of a csv files with or without PAIN flags. A case study focused on TDP1 inhibitors

### Content   <a name="content"></a>

1. [Load and analyse PubChem BioAssay GPR151 protein activators data](#1)
2. [Create a data frame with targets](#2)
3. [Asign PAIN flags](#3)
4. [Integrate PAINS and IUPACS](#4)
5. [Check if a sample with IUPAC is PAIN](#5)

### Load and analyse PubChem BioAssay data <a name="1"></a>

In [1]:
import pandas as pd 

# load the PubChem AID 686978 bioassy dataset
# https://pubchem.ncbi.nlm.nih.gov/bioassay/686978
df = pd.read_csv('AID_686978_data.csv', low_memory=False, on_bad_lines='skip')

# To avoid truncation of some columns during data frame display
pd.set_option('display.max_columns', None) 

# Display the data frame
print('Shape of the data frame: ', df.shape)
df.head()

Shape of the data frame:  (424003, 48)

,PUBCHEM_RESULT_TAG,PUBCHEM_SID,PUBCHEM_CID,PUBCHEM_EXT_DATASOURCE_SMILES,PUBCHEM_ACTIVITY_OUTCOME,PUBCHEM_ACTIVITY_SCORE,PUBCHEM_ACTIVITY_URL,PUBCHEM_ASSAYDATA_COMMENT,Phenotype,Potency,Efficacy,Analysis Comment,Activity_Score,Curve_Description,Fit_LogAC50,Fit_HillSlope,Fit_R2,Fit_InfiniteActivity,Fit_ZeroActivity,Fit_CurveClass,Excluded_Points,Max_Response,Activity at 0.0000295000 uM,Activity at 0.0000590000 uM,Activity at 0.0001503265 uM,Activity at 0.0002712146 uM,Activity at 0.0005895491 uM,Activity at 0.00117 uM,Activity at 0.00179 uM,Activity at 0.00299 uM,Activity at 0.00672 uM,Activity at 0.014 uM,Activity at 0.026 uM,Activity at 0.040 uM,Activity at 0.074 uM,Activity at 0.167 uM,Activity at 0.363 uM,Activity at 0.628 uM,Activity at 0.975 uM,Activity at 1.849 uM,Activity at 4.119 uM,Activity at 9.037 uM,Activity at 15.83 uM,Activity at 21.08 uM,Activity at 46.23 uM,Activity at 92.54 uM,Activity at 165.6 uM,Compound QC;;;;
0,1,109967258,50897788.0,CNCC1=NC2=C(C=C(C=C2)Cl)C(=N1)C3=CC=CN3,Active,42,http://assay.nih.gov/htsws/rest/display/dd-tdp...,NaN,Inhibitor,14.1254,136.5470,NaN,42.0,Partial curve; high efficacy,-4.850,1.0100,0.9948,-134.4880,2.0597,-2.1,0 0 0 0 0,-106.3110,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0597,NaN,NaN,NaN,NaN,0.5007,NaN,NaN,-17.4373,NaN,-48.5138,NaN,NaN,-106.3110,NaN,NaN,QC'd by AA Pharmaceuticals;;;
1,2,144206324,65628.0,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O,Active,41,http://assay.nih.gov/htsws/rest/display/dd-tdp...,NaN,Inhibitor,18.8375,82.1468,NaN,41.0,Partial curve; high efficacy,-4.725,1.9887,0.9829,-82.6097,-0.4629,-2.1,0 0 0 0 0 0 0 0,-70.9545,NaN,NaN,NaN,NaN,-3.2819,NaN,NaN,1.1641,NaN,5.8554,NaN,NaN,-1.8326,NaN,-4.9853,NaN,NaN,0.0798,NaN,-16.3921,NaN,NaN,-70.9545,NaN,NaN,QC'd by ACC;;;
2,3,144206325,14708.0,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C)O)CC[C@@...,Inconclusive,10,http://assay.nih.gov/htsws/rest/display/dd-tdp...,NaN,Inhibitor,21.1360,39.2903,NaN,10.0,Single point of activity,-4.675,2.7868,0.9357,-43.4549,-4.1646,-3.0,0 0 0 0 0 0 0 0,-39.2270,NaN,NaN,NaN,NaN,-4.1400,NaN,NaN,-5.7369,NaN,0.1681,NaN,NaN,-8.2838,NaN,-6.9258,NaN,NaN,1.0188,NaN,-7.8647,NaN,NaN,-39.2270,NaN,NaN,QC'd by ACC;;;;
3,4,144206326,3085168.0,CC1=NC=C(C(=N1)N)CN(C=O)/C(=C(\CCO)/SS/C(=C(/C...,Inactive,0,http://assay.nih.gov/htsws/rest/display/dd-tdp...,NaN,Inactive,NaN,NaN,NaN,0.0,NaN,NaN,4.9549,0.6177,2.0768,-13.6113,4.0,0 0 0 0 0 0 0 1,-5.7844,NaN,NaN,NaN,NaN,-11.9232,NaN,NaN,-14.5799,NaN,8.2225,NaN,NaN,4.9756,NaN,4.8996,NaN,NaN,-10.1081,NaN,3.3805,NaN,NaN,-5.7844,NaN,NaN,QC'd by ACC;;;;
4,5,144206327,2449.0,CC1=C(C(=O)C(=C(C1=O)C)C(CCCCCC(=O)O)C2=CC=CC=...,Inconclusive,10,http://assay.nih.gov/htsws/rest/display/dd-tdp...,NaN,Inhibitor,26.6086,77.9682,NaN,10.0,Single point of activity,-4.575,3.5117,0.9609,-82.1111,-4.1429,-3.0,0 0 0 0 0 0 0 0,-72.3569,NaN,NaN,NaN,NaN,-10.6429,NaN,NaN,-2.5661,NaN,-11.5870,NaN,NaN,-4.3838,NaN,1.2149,NaN,NaN,1.7567,NaN,-5.8883,NaN,NaN,-72.3569,NaN,NaN,QC'd by ACC;;;;

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 424003 entries, 0 to 424002
Data columns (total 48 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   PUBCHEM_RESULT_TAG             424003 non-null  int64
 1   PUBCHEM_SID                    424003 non-null  int64
 2   PUBCHEM_CID                    423975 non-null  float64
 3   PUBCHEM_EXT_DATASOURCE_SMILES  423975 non-null  object
 4   PUBCHEM_ACTIVITY_OUTCOME       424003 non-null  object
 5   PUBCHEM_ACTIVITY_SCORE         424003 non-null  int64
 6   PUBCHEM_ACTIVITY_URL           424003 non-null  object
 7   PUBCHEM_ASSAYDATA_COMMENT      0 non-null       float64
 8   Phenotype                      424003 non-null  object
 9   Potency                        175189 non-null  float64
 10  Efficacy                       175189 non-null  float64
 11  Analysis Comment               0 non-null       float64
 12  Activity_Score                 423178 non-null  float64
 13  Curve_Description              181619 non-null  object
 14  Fit_LogAC50                    201416 non-null  float64
 15  Fit_HillSlope                  402791 non-null  float64
 16  Fit_R2                         402791 non-null  float64
 17  Fit_InfiniteActivity           402791 non-null  float64
 18  Fit_ZeroActivity               402791 non-null  float64
 19  Fit_CurveClass                 424003 non-null  float64
 20  Excluded_Points                402791 non-null  object
 21  Max_Response                   424003 non-null  float64
 22  Activity at 0.0000295000 uM    17 non-null      float64
 23  Activity at 0.0000590000 uM    1 non-null       float64
 24  Activity at 0.0001503265 uM    20 non-null      float64
 25  Activity at 0.0002712146 uM    524 non-null     float64
 26  Activity at 0.0005895491 uM    4330 non-null    float64
 27  Activity at 0.00117 uM         2007 non-null    float64
 28  Activity at 0.00179 uM         221 non-null     float64
 29  Activity at 0.00299 uM         413492 non-null  float64
 30  Activity at 0.00672 uM         2214 non-null    float64
 31  Activity at 0.014 uM           18879 non-null   float64
 32  Activity at 0.026 uM           369 non-null     float64
 33  Activity at 0.040 uM           1978 non-null    float64
 34  Activity at 0.074 uM           17897 non-null   float64
 35  Activity at 0.167 uM           2223 non-null    float64
 36  Activity at 0.363 uM           421561 non-null  float64
 37  Activity at 0.628 uM           362 non-null     float64
 38  Activity at 0.975 uM           1989 non-null    float64
 39  Activity at 1.849 uM           420261 non-null  float64
 40  Activity at 4.119 uM           2247 non-null    float64
 41  Activity at 9.037 uM           420223 non-null  float64
 42  Activity at 15.83 uM           339 non-null     float64
 43  Activity at 21.08 uM           1868 non-null    float64
 44  Activity at 46.23 uM           422907 non-null  float64
 45  Activity at 92.54 uM           286 non-null     float64
 46  Activity at 165.6 uM           13 non-null      float64
 47  Compound QC;;;;                424003 non-null  object
dtypes: float64(38), int64(3), object(7)
memory usage: 155.3+ MB

In [3]:
# Remove missing values
df = df[df['PUBCHEM_CID'].notna()]
df.shape

(423975, 48)

In [4]:
# Remove duplicates without keeping a sample ofthem and reset the indexes 
df = df.drop_duplicates(subset='PUBCHEM_CID', keep=False).reset_index(drop=True)
df.shape

(410564, 48)

In [5]:
# Turn CID float data type into integer
df['PUBCHEM_CID'] = df['PUBCHEM_CID'].astype('int64')

In [6]:
# Filter inhibitors 
df = df[['PUBCHEM_CID',
         'PUBCHEM_SID',
         'PUBCHEM_EXT_DATASOURCE_SMILES',
         'PUBCHEM_ACTIVITY_OUTCOME']] 
df.shape # 646675

(410564, 4)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 410564 entries, 0 to 410563
Data columns (total 4 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   PUBCHEM_CID                    410564 non-null  int64
 1   PUBCHEM_SID                    410564 non-null  int64
 2   PUBCHEM_EXT_DATASOURCE_SMILES  410564 non-null  object
 3   PUBCHEM_ACTIVITY_OUTCOME       410564 non-null  object
dtypes: int64(2), object(2)
memory usage: 12.5+ MB

[<a href="#content">Back to top</a>]

## Create a data frame with targets <a name="2"></a>

In [8]:
# Fix data type issue in the raw data
df['PUBCHEM_ACTIVITY_OUTCOME'] = df['PUBCHEM_ACTIVITY_OUTCOME'].astype(str) 
# Get unique values from 'column1'
unique_values = df['PUBCHEM_ACTIVITY_OUTCOME'].unique()
unique_values

array(['Active', 'Inconclusive', 'Inactive'], dtype=object)

In [9]:
# Create a dictionary with the desired column names
df.rename(columns={'PUBCHEM_CID':'CID',
                   'PUBCHEM_SID':'SID',
                   'PUBCHEM_EXT_DATASOURCE_SMILES':'SMILES',
                   'PUBCHEM_ACTIVITY_OUTCOME':'target'}, inplace=True)

# Set the option to explicitly handle downcasting
pd.set_option('future.no_silent_downcasting', True)

# Create a mapping dictionary to replace string values with numeric values
mapping = {'Active': 1, 'Inactive': 0, 'Inconclusive':2}

# Replace string values with numeric values using the mapping dictionary
df['target'] = df['target'].replace(mapping)

# Display the data frame
print('Shape of the data frame: ', df.shape)
df.head()

Shape of the data frame:  (410564, 4)

,CID,SID,SMILES,target
0,50897788,109967258,CNCC1=NC2=C(C=C(C=C2)Cl)C(=N1)C3=CC=CN3,1
1,65628,144206324,CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O,1
2,14708,144206325,C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C)O)CC[C@@...,2
3,3085168,144206326,CC1=NC=C(C(=N1)N)CN(C=O)/C(=C(\CCO)/SS/C(=C(/C...,0
4,2449,144206327,CC1=C(C(=O)C(=C(C1=O)C)C(CCCCCC(=O)O)C2=CC=CC=...,2

In [10]:
# Turn CID float data type into integer
df['target'] = pd.to_numeric(df['target'])

In [11]:
# Class distribution
df['target'].value_counts()

target
0    236226
2    112867
1     61471
Name: count, dtype: int64

In [12]:
# Dataframe shape
df_1 = df[df['target']==1]
df_1.shape

(61471, 4)

[<a href="#content">Back to top</a>]

## Asign PAIN flags  <a name="3"></a>

In [13]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem.FilterCatalog import FilterCatalog, FilterCatalogParams

# Define the PAINS Filter Source
# create a filter catalog for Pan Assay Interference Substructures (PAINS).
params = FilterCatalogParams()
params.AddCatalog(FilterCatalogParams.FilterCatalogs.PAINS)
pains_catalog = FilterCatalog(params)

def check_pains(smiles):
    """
    Checks a given SMILES string against the RDKit PAINS filter catalog.
    
    Returns:
        bool: True if the compound is flagged as a PAIN, False otherwise.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return False  # Cannot process invalid SMILES
    
    # Run the molecule against the PAINS catalog
    is_pain = pains_catalog.HasMatch(mol)
    return is_pain


# Apply the RDKit check to generate the actual PAIN flag
# Create a new boolean column: True if it is a PAIN, False otherwise.
df['PAIN_flag'] = df['SMILES'].apply(check_pains)

# Convert the boolean flag to 'PAIN' / 'No' for clearer output
df['PAIN_flag'] = df['PAIN_flag'].apply(lambda x: 'PAIN' if x else 'No')

print("--- Original DataFrame with RDKit PAINS Check Results ---")
print(df)
print("-" * 70)
print(f"Total compounds: {len(df)}")
print(f"PAIN flagged compounds: {df['PAIN_flag'].eq('PAIN').sum()}")
print("-" * 70)

[13:55:18] WARNING: not removing hydrogen atom without neighbors
[13:55:18] WARNING: not removing hydrogen atom without neighbors
[14:05:47] Explicit valence for atom # 3 Si, 8, is greater than permitted
[14:09:45] WARNING: not removing hydrogen atom without neighbors
[14:09:46] WARNING: not removing hydrogen atom without neighbors
[14:09:46] WARNING: not removing hydrogen atom without neighbors

--- Original DataFrame with RDKit PAINS Check Results ---
             CID        SID  \
0       50897788  109967258
1          65628  144206324
2          14708  144206325
3        3085168  144206326
4           2449  144206327
...          ...        ...
410559  25246382   57655062
410560  25246383   57655063
410561  25246384   57655064
410562  25246385   57655065
410563   1013376  144206362

                                                   SMILES  target PAIN_flag
0                 CNCC1=NC2=C(C=C(C=C2)Cl)C(=N1)C3=CC=CN3       1        No
1              CN1C2=C(C=C(C=C2)N(CCCl)CCCl)N=C1CCCC(=O)O       1        No
2       C[C@]12CC[C@H]3[C@H]([C@@H]1CC[C@]2(C)O)CC[C@@...       2        No
3       CC1=NC=C(C(=N1)N)CN(C=O)/C(=C(\CCO)/SS/C(=C(/C...       0        No
4       CC1=C(C(=O)C(=C(C1=O)C)C(CCCCCC(=O)O)C2=CC=CC=...       2      PAIN
...                                                   ...     ...       ...
410559  CC(=O)NC1=CC=C(C=C1)OCC2=C(C=CC(=C2)C3=NC4=C(C...       1        No
410560  CC(=O)NC1=CC=C(C=C1)OCC2=C(C=CC(=C2)CN(CC3=CC=...       2        No
410561  CC(=O)NC1=CC=C(C=C1)C(=O)N(CC2=CC=CC=C2)CC3=CC...       2        No
410562  CC(=O)NC1=CC=C(C=C1)OCC2=C(C=CC(=C2)CN(CC3=CC=...       1        No
410563  CC(=O)NC1=CC=C(C=C1)NC(=S)NC(=O)C2=CC=C(C=C2)C...       0        No

[410564 rows x 5 columns]
----------------------------------------------------------------------
Total compounds: 410564
PAIN flagged compounds: 21761
----------------------------------------------------------------------

In [14]:
# Class distribution
df['target'].value_counts()

target
0    236226
2    112867
1     61471
Name: count, dtype: int64

[<a href="#content">Back to top</a>]

 ## Integrate PAINS and IUPACS <a name="4"></a>

In [15]:
# load the PubChem provided data for the samples used in the bioassay
df_iupacs = pd.read_csv('IUPACS_TDP1_raw.csv', low_memory=False, on_bad_lines='skip')

# Display the data frame
print('Shape of the data frame: ', df_iupacs.shape)
df_iupacs.head()

Shape of the data frame:  (297697, 38)

,Compound_CID,Name,Synonyms,Molecular_Weight,Molecular_Formula,Polar_Area,Complexity,XLogP,Heavy_Atom_Count,H-Bond_Donor_Count,H-Bond_Acceptor_Count,Rotatable_Bond_Count,InChI,SMILES,InChIKey,IUPAC_Name,Exact_Mass,Monoisotopic_Mass,Charge,Covalent_Unit_Count,Isotopic_Atom_Count,Total_Atom_Stereo_Count,Defined_Atom_Stereo_Count,Undefined_Atom_Stereo_Count,Total_Bond_Stereo_Count,Defined_Bond_Stereo_Count,Undefined_Bond_Stereo_Count,Linked_PubChem_Literature_Count,Linked_PubChem_Patent_Count,Linked_PubChem_Patent_Family_Count,MeSH_Headings,Annotation_Content,Annotation_Type_Count,Linked_BioAssays,Create_Date,Data_Source,Data_Source_Category,Tagged_by_PubChem
0,7779314,4-(azepane-1-carbonyl)-N-(2-fluorophenyl)benze...,MLS001156782|CHEMBL1899975|HMS3011I09|AKOS0009...,376.40,C19H21FN2O3S,74.9,562.0,3.2,26,1,5,4,InChI=1S/C19H21FN2O3S/c20-17-7-3-4-8-18(17)21-...,C1CCCN(CC1)C(=O)C2=CC=C(C=C2)S(=O)(=O)NC3=CC=C...,SWSSNSNCRHTDTB-UHFFFAOYSA-N,4-(azepane-1-carbonyl)-N-(2-fluorophenyl)benze...,376.125692,376.125692,0,1,0,0,0,0,0,0,0,2,0,0,NaN,Biological Test Results|Classification|Literature,3,1511|1554|1662|1663|1672|1813|1814|1832|1850|1...,20060729,ABI Chem|AKos Consulting & Solutions|Aurora Fi...,Chemical Vendors|Curation Efforts|Governmental...,NaN
1,973113,1-(4-Methoxyphenyl)-3-[2-(4-methylpiperidin-1-...,CHEMBL1482486|MLS000664918|A3529/0149457|1-(4-...,307.50,C16H25N3OS,68.6,311.0,2.8,21,2,3,5,InChI=1S/C16H25N3OS/c1-13-7-10-19(11-8-13)12-9...,CC1CCN(CC1)CCNC(=S)NC2=CC=C(C=C2)OC,SGBRBNIUXHHEHT-UHFFFAOYSA-N,1-(4-methoxyphenyl)-3-[2-(4-methylpiperidin-1-...,307.171834,307.171834,0,1,0,0,0,0,0,0,0,3,0,0,NaN,Biological Test Results|Chemical and Physical ...,6,485|631|731|757|758|759|760|761|764|781|782|79...,20050709,ABI Chem|AKos Consulting & Solutions|Aurora Fi...,Chemical Vendors|Curation Efforts|Governmental...,NaN
2,2351911,"3-[(4-Fluorobenzoyl)amino]-4-oxopyrido[1,2-a]p...",Oprea1_241552|MLS000775117|CHEMBL1523645|HMS27...,327.27,C16H10FN3O4,99.1,715.0,0.5,24,2,6,3,InChI=1S/C16H10FN3O4/c17-11-4-1-9(2-5-11)14(21...,C1=CC(=CC=C1C(=O)NC2=CN=C3C=CC(=CN3C2=O)C(=O)O)F,GWOMBBYXRHVSQN-UHFFFAOYSA-N,"3-[(4-fluorobenzoyl)amino]-4-oxopyrido[1,2-a]p...",327.065534,327.065534,0,1,0,0,0,0,0,0,0,2,0,0,NaN,Biological Test Results|Classification|Literat...,4,485|781|782|798|800|873|880|940|1021|1022|1046...,20050715,ABI Chem|AKos Consulting & Solutions|Ambinter|...,Chemical Vendors|Curation Efforts|Governmental...,NaN
3,16008588,"1-(2-chlorophenyl)-N-(3,5-dimethoxyphenyl)-3,6...",CHEMBL1437055|HMS1829M12|AKOS001814472|NCGC001...,436.90,C23H21ClN4O3,78.3,614.0,4.7,31,1,5,5,InChI=1S/C23H21ClN4O3/c1-13-9-18(23(29)26-15-1...,CC1=CC(=C2C(=NN(C2=N1)C3=CC=CC=C3Cl)C)C(=O)NC4...,CYKCJKHZXQFVQV-UHFFFAOYSA-N,"1-(2-chlorophenyl)-N-(3,5-dimethoxyphenyl)-3,6...",436.130218,436.130218,0,1,0,0,0,0,0,0,0,3,0,0,NaN,Biological Test Results|Classification|Literat...,5,445|902|903|904|924|1458|1460|1463|1468|1469|1...,20070402,AKos Consulting & Solutions|Ambinter|Aurora Fi...,Chemical Vendors|Curation Efforts|Governmental...,NaN
4,1245119,1-(Cyclobutylcarbonyl)-4-(4-methylbenzyl)piper...,MLS000065652|CHEMBL1490806|HMS2451C09|STK46356...,272.40,C17H24N2O,23.6,324.0,2.4,20,0,2,3,InChI=1S/C17H24N2O/c1-14-5-7-15(8-6-14)13-18-9...,CC1=CC=C(C=C1)CN2CCN(CC2)C(=O)C3CCC3,RZFYNMIQFCNTJV-UHFFFAOYSA-N,cyclobutyl-[4-[(4-methylphenyl)methyl]piperazi...,272.188863,272.188863,0,1,0,0,0,0,0,0,0,1,0,0,NaN,Biological Test Results|Classification|Literat...,4,360|361|368|373|374|375|411|422|425|429|430|43...,20050710,ABI Chem|AgroIntelBioScan.com|AKos Consulting ...,Chemical Vendors|Curation Efforts|Governmental...,NaN

In [16]:
df_pains = pd.merge(df, df_iupacs, on ='SMILES')

In [17]:
df_pains = df_pains[['CID', 'SID',  'IUPAC_Name', 'PAIN_flag']]
df_pains.to_csv('HF_TDP1_inhibitors_PAINflags_IUPAC_CID_SID.csv', index=False)

In [18]:
df_pains.shape

(297696, 4)

In [19]:
df_pains.head()

,CID,SID,IUPAC_Name,PAIN_flag
0,50897788,109967258,1-[6-chloro-4-(1H-pyrrol-2-yl)quinazolin-2-yl]...,No
1,65628,144206324,4-[5-[bis(2-chloroethyl)amino]-1-methylbenzimi...,No
2,3085168,144206326,N-[(4-amino-2-methylpyrimidin-5-yl)methyl]-N-[...,No
3,54158,144206328,"2-[[2-(3-bromo-2,4,6-trimethylanilino)-2-oxoet...",No
4,92140,144206329,"[(2R,3S,4S)-2,3,4-tri(butanoyloxy)-5-(7,8-dime...",No

[<a href="#content">Back to top</a>]

## Check if a sample with IUPAC is PAIN <a name="5"></a>

In [21]:
# # IUPAs with imidazo
# # The list was generataed from the file: 5.5.TDP1_group_all_dfs.ipynb
# targets = ['2-(1H-imidazo[4,5-b]pyridin-2-ylsulfanyl)-N-(2-phenylethyl)butanamide', 
#           'N-(4-methoxyphenyl)-3-(4-methylphenyl)-6,7,8,9-tetrahydro-5H-imidazo[1,5-a]azepine-1-carboxamide', 
#           '5-ethyl-N-(2-imidazo[1,2-a]pyridin-2-ylethyl)thiophene-2-sulfonamide', 
#           '2-methoxy-4-[5-(3-methylanilino)imidazo[2,1-b][1,3]thiazol-6-yl]phenol', 
#           '2-(1H-imidazo[4,5-b]pyridin-2-ylsulfanyl)-N-(2-methoxyphenyl)acetamide']

# IUPAs with carboxamide
# The list was generataed from the file: 5.5.TDP1_group_all_dfs.ipynb
targets = ['1-(2-chlorophenyl)-N-(3,5-dimethoxyphenyl)-3,6-dimethylpyrazolo[3,4-b]pyridine-4-carboxamide', 
           '5-(1,3-benzodioxol-5-yl)-N-(2-methylpropyl)-1,2-oxazole-3-carboxamide',
           '4-benzyl-N-[2-(4-chlorophenyl)ethyl]-3-oxo-1,4-benzothiazine-6-carboxamide',
           '1-benzyl-6-methyl-2-oxo-3-[2-oxo-2-(4-phenylbutylamino)ethyl]-N,N-di(propan-2-yl)-3,4-dihydropyridine-5-carboxamide', 
           '2-(4-ethylphenyl)-5-(hydroxymethyl)-N-(thiophen-2-ylmethyl)triazole-4-carboxamide']

# # IUPAs with oxonaphthalen
# # The list was generataed from the file: 5.5.TDP1_group_all_dfs.ipynb
# targets = ['N-[3-bromo-1-di(propan-2-yloxy)phosphoryl-4-oxonaphthalen-1-yl]benzenesulfonamide',
#            'N-(1-dibutoxyphosphoryl-4-oxonaphthalen-1-yl)benzenesulfonamide',
#            '(NZ)-N-(3-anilino-4-oxonaphthalen-1-ylidene)thiophene-2-sulfonamide',
#            '1,5-dimethyl-4-[(4-oxonaphthalen-1-ylidene)amino]-2-phenylpyrazol-3-one',
#           '(NZ)-N-[3-(4-methylanilino)-4-oxonaphthalen-1-ylidene]thiophene-2-sulfonamide']

# #  IUPACS with ylbutanediamide
# #  The list was generataed from the file: 5.5.TDP1_group_all_dfs.ipynb
# targets = ["N'-[1-(4-fluorophenyl)-2-(2-methylbutan-2-ylamino)-2-oxoethyl]-N'-(furan-2-ylmethyl)-N-pyridin-2-ylbutanediamide",
#            "N'-(4-methoxyphenyl)-N'-[2-oxo-2-(2-phenylethylamino)ethyl]-N-pyridin-2-ylbutanediamide",
#            "N'-[2-(2-methoxyethylamino)-1-(4-methoxyphenyl)-2-oxoethyl]-N'-(oxolan-2-ylmethyl)-N-pyridin-2-ylbutanediamide",
#            "N'-(2,3-dihydro-1,4-benzodioxin-6-yl)-N'-[2-(3-methylbutylamino)-2-oxoethyl]-N-pyridin-2-ylbutanediamide",
#            "N'-[2-(tert-butylamino)-1-(4-methoxyphenyl)-2-oxoethyl]-N'-cyclohexyl-N-pyridin-2-ylbutanediamide"]

condition = df_pains['IUPAC_Name'].isin(targets)

# Apply the condition (Boolean Indexing)
# pandas returns a new DataFrame containing only the rows where the condition is True.
filtered_rows = df_pains[condition]

# Print the result
# Check if any row was found
if not filtered_rows.empty:
    # Use to_string() to ensure the entire row content is printed, even if it's wide
    print(filtered_rows.to_string(index=False)) 
else:
    print(f"No rows found for the specified IDs.")

print("\n" + "=" * 30)

     CID      SID                                                                                                          IUPAC_Name PAIN_flag
15993269 49667698                                               5-(1,3-benzodioxol-5-yl)-N-(2-methylpropyl)-1,2-oxazole-3-carboxamide        No
16008588 24384816                        1-(2-chlorophenyl)-N-(3,5-dimethoxyphenyl)-3,6-dimethylpyrazolo[3,4-b]pyridine-4-carboxamide        No
16014225 24391772                                   2-(4-ethylphenyl)-5-(hydroxymethyl)-N-(thiophen-2-ylmethyl)triazole-4-carboxamide        No
 4086767 24415205                                          4-benzyl-N-[2-(4-chlorophenyl)ethyl]-3-oxo-1,4-benzothiazine-6-carboxamide        No
46904149 99359587 1-benzyl-6-methyl-2-oxo-3-[2-oxo-2-(4-phenylbutylamino)ethyl]-N,N-di(propan-2-yl)-3,4-dihydropyridine-5-carboxamide        No

==============================

In [22]:
# filtered_rows.to_csv('PAINs_imidazo.csv', index=False)
filtered_rows.to_csv('PAINs_carboxamide.csv', index=False)
# filtered_rows.to_csv('PAINs_oxonaphthalen.csv', index=False)
# filtered_rows.to_csv('PAINs_ylbutanediamide.csv', index=False)

[<a href="#content">Back to top</a>]